import React, { useEffect, useState } from 'react';
import toast from 'react-hot-toast';
import { getQuotes, deleteQuote } from '../services/api';

export default function QuoteHistory() {
  const [quotes, setQuotes] = useState([]);
  const [selected, setSelected] = useState(null);
  const [search, setSearch] = useState('');
  const [loading, setLoading] = useState(true);

  const load = () => {
    setLoading(true);
    getQuotes().then(r => setQuotes(r.data)).finally(() => setLoading(false));
  };

  useEffect(() => { load(); }, []);

  const filtered = quotes.filter(q =>
    q.quote_name.toLowerCase().includes(search.toLowerCase()) ||
    (q.customer_name || '').toLowerCase().includes(search.toLowerCase()) ||
    (q.cycle_model || '').toLowerCase().includes(search.toLowerCase())
  );

  const handleDelete = async (id) => {
    if (!window.confirm('Delete this quote?')) return;
    try {
      await deleteQuote(id);
      toast.success('Quote deleted');
      if (selected?.id === id) setSelected(null);
      load();
    } catch { toast.error('Failed to delete'); }
  };

  const handlePrint = (quote) => {
    const win = window.open('', '_blank');
    win.document.write(`
      <html><head><title>Quote - ${quote.quote_name}</title>
      <style>
        body { font-family: Arial, sans-serif; padding: 40px; color: #222; }
        h1 { color: #2d6a4f; margin-bottom: 4px; }
        .meta { color: #666; font-size: 14px; margin-bottom: 24px; }
        table { width: 100%; border-collapse: collapse; margin-bottom: 20px; }
        th { background: #2d6a4f; color: white; padding: 10px; text-align: left; }
        td { padding: 9px 10px; border-bottom: 1px solid #eee; }
        .total { font-size: 20px; font-weight: bold; text-align: right; color: #2d6a4f; }
        .footer { margin-top: 40px; color: #999; font-size: 12px; }
      </style>
      </head><body>
      <h1>Hero Cycles — Price Quote</h1>
      <div class="meta">
        <strong>Quote:</strong> ${quote.quote_name} &nbsp;|&nbsp;
        <strong>Customer:</strong> ${quote.customer_name || '—'} &nbsp;|&nbsp;
        <strong>Model:</strong> ${quote.cycle_model || '—'} &nbsp;|&nbsp;
        <strong>Date:</strong> ${new Date(quote.created_at).toLocaleDateString('en-IN')}
      </div>
      <table>
        <tr><th>Part</th><th>SKU</th><th>Category</th><th>Qty</th><th>Unit Price</th><th>Total</th></tr>
        ${quote.items.map(item => `
          <tr>
            <td>${item.part_name}</td>
            <td>${item.part_sku}</td>
            <td>${item.category_name}</td>
            <td>${item.quantity}</td>
            <td>₹${item.unit_price.toLocaleString('en-IN')}</td>
            <td>₹${item.total_price.toLocaleString('en-IN')}</td>
          </tr>
        `).join('')}
      </table>
      <div style="text-align:right">
        <div>Parts Total: ₹${quote.total_price.toLocaleString('en-IN')}</div>
        ${quote.margin_percent > 0 ? `<div>Margin (${quote.margin_percent}%): +₹${(quote.final_price - quote.total_price).toLocaleString('en-IN')}</div>` : ''}
        <div class="total">FINAL: ₹${quote.final_price.toLocaleString('en-IN')}</div>
      </div>
      ${quote.notes ? `<div style="margin-top:16px;padding:12px;background:#f0fff4;border-radius:6px"><strong>Notes:</strong> ${quote.notes}</div>` : ''}
      <div class="footer">Generated by Hero Cycles Pricing Engine · ${new Date().toLocaleString('en-IN')}</div>
      </body></html>
    `);
    win.document.close();
    win.print();
  };

  if (loading) return <div className="loading">⏳ Loading quotes…</div>;

  return (
    <div>
      <div className="page-header">
        <div className="page-title">📄 Quote History</div>
        <div className="page-sub">View, print and manage all saved quotes</div>
      </div>

      <div style={{ display: 'grid', gridTemplateColumns: selected ? '1fr 420px' : '1fr', gap: 24 }}>
        {/* Quote List */}
        <div>
          <div className="card mb-4">
            <div className="search-bar">
              <span className="search-icon">🔍</span>
              <input className="form-input" placeholder="Search by quote name, customer, model…" value={search} onChange={e => setSearch(e.target.value)} />
            </div>
          </div>

          <div className="card">
            {filtered.length === 0 ? (
              <div className="empty-state">
                <div className="empty-state-icon">📄</div>
                <div className="empty-state-text">{search ? 'No matching quotes' : 'No quotes saved yet. Go to Pricing Engine to create one!'}</div>
              </div>
            ) : (
              <div className="table-wrapper">
                <table>
                  <thead>
                    <tr><th>Quote Name</th><th>Customer</th><th>Model</th><th>Parts Total</th><th>Final Price</th><th>Date</th><th>Actions</th></tr>
                  </thead>
                  <tbody>
                    {filtered.map(q => (
                      <tr key={q.id} style={{ cursor: 'pointer', background: selected?.id === q.id ? '#f0fff4' : '' }} onClick={() => setSelected(q)}>
                        <td><strong>{q.quote_name}</strong></td>
                        <td>{q.customer_name || <span className="text-muted">—</span>}</td>
                        <td>{q.cycle_model || <span className="text-muted">—</span>}</td>
                        <td>₹{q.total_price.toLocaleString('en-IN')}</td>
                        <td><strong className="text-green">₹{q.final_price.toLocaleString('en-IN')}</strong>
                          {q.margin_percent > 0 && <span style={{ fontSize: 11, color: '#a0aec0', marginLeft: 4 }}>+{q.margin_percent}%</span>}
                        </td>
                        <td style={{ fontSize: 12, color: '#718096' }}>{new Date(q.created_at).toLocaleDateString('en-IN')}</td>
                        <td onClick={e => e.stopPropagation()}>
                          <div style={{ display: 'flex', gap: 6 }}>
                            <button className="btn btn-sm btn-secondary" title="Print" onClick={() => handlePrint(q)}>🖨️</button>
                            <button className="btn btn-sm btn-danger" onClick={() => handleDelete(q.id)}>🗑</button>
                          </div>
                        </td>
                      </tr>
                    ))}
                  </tbody>
                </table>
              </div>
            )}
          </div>
        </div>

        {/* Quote Detail Panel */}
        {selected && (
          <div>
            <div className="card">
              <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'flex-start', marginBottom: 16 }}>
                <div>
                  <div style={{ fontWeight: 700, fontSize: 16 }}>{selected.quote_name}</div>
                  <div style={{ fontSize: 12, color: '#718096', marginTop: 2 }}>
                    {new Date(selected.created_at).toLocaleString('en-IN')}
                  </div>
                </div>
                <button onClick={() => setSelected(null)} style={{ background: 'none', border: 'none', cursor: 'pointer', fontSize: 18, color: '#a0aec0' }}>✕</button>
              </div>

              <div style={{ background: '#f7fafc', borderRadius: 8, padding: 12, marginBottom: 16, fontSize: 13 }}>
                {selected.customer_name && <div><strong>Customer:</strong> {selected.customer_name}</div>}
                {selected.cycle_model && <div><strong>Model:</strong> {selected.cycle_model}</div>}
                {selected.notes && <div style={{ marginTop: 6, color: '#718096' }}>{selected.notes}</div>}
              </div>

              <div className="card-title">Parts Breakdown</div>
              {selected.items.map((item, i) => (
                <div key={i} className="quote-item">
                  <div className="quote-item-left">
                    <div className="quote-item-name">{item.part_name}</div>
                    <div className="quote-item-meta">{item.part_sku} · {item.category_name} · ×{item.quantity}</div>
                  </div>
                  <div className="quote-item-price">₹{item.total_price.toLocaleString('en-IN')}</div>
                </div>
              ))}

              <hr className="divider" />

              <div style={{ fontSize: 13 }}>
                <div style={{ display: 'flex', justifyContent: 'space-between', marginBottom: 6 }}>
                  <span>Parts Total</span><span>₹{selected.total_price.toLocaleString('en-IN')}</span>
                </div>
                {selected.margin_percent > 0 && (
                  <div style={{ display: 'flex', justifyContent: 'space-between', marginBottom: 6, color: '#718096' }}>
                    <span>Margin ({selected.margin_percent}%)</span>
                    <span>+₹{(selected.final_price - selected.total_price).toLocaleString('en-IN')}</span>
                  </div>
                )}
              </div>
              <div className="quote-total">
                <span>FINAL PRICE</span>
                <span>₹{selected.final_price.toLocaleString('en-IN')}</span>
              </div>

              <button className="btn btn-outline" style={{ width: '100%', justifyContent: 'center', marginTop: 16 }} onClick={() => handlePrint(selected)}>
                🖨️ Print / Export Quote
              </button>
            </div>
          </div>
        )}
      </div>
    </div>
  );
}
